<?php
/**
 * @file
 * Code for the Deploy Add-on module.
 */

include_once 'deploy_addon.features.inc';

/**
 * Implements hook_deploy_auto_plan_status_alter().
 */
function deploy_addon_deploy_auto_plan_status_alter(&$status, $type, $entity) {
  // Don't allow users 0 and 1 into the Deployment Plan.
  if ($type == 'user' && in_array($entity->uid, array(0, 1))) {
    $status = FALSE;
  }
}

/**
 * Implements hook_user_presave().
 */
function deploy_addon_user_presave(&$edit, $account, $category) {
  // Block users belonging to roles we don't want active on specific environments.
  $roles = variable_get('deploy_addon_user_roles_block', NULL);

  if (is_array($roles)) {
    foreach ($roles as $role) {
      if (in_array($role, $account->roles)) {
        $edit['status'] = 0;
      }
    }
  }

  // Remove user roles we don't want on specific environments.
  $roles_to_remove = variable_get('deploy_addon_user_roles_to_remove', NULL);
  if (is_array($roles_to_remove)) {
    $drupal_roles = user_roles(TRUE);
    foreach ($roles_to_remove as $role) {
      $rid = array_search($role, $drupal_roles);
      if (array_key_exists($rid, $edit['roles'])) {
        unset($edit['roles'][$rid]);
      }
    }
  }
}
